// displayed name
name: Android Build

// what actions should run in response to
on: pull_request

// tasks that will be run on each pull request
jobs:
  build:
    // define the invironemnt
    runs-on: ubuntu-latest
    // the tasks it self
    steps:
      - uses: actions/checkout@v1 // gets the code from the repo to the invironment
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name : Build Project
        run : ./gradlew assemble